import React, { useState, useEffect, useCallback } from 'react';
import { motion, useScroll, useTransform, useSpring } from 'framer-motion';
import { FiBookOpen } from 'react-icons/fi';

// ── Page data ──────────────────────────────────────────────────────────────────
const pages = [
  {
    id: 0,
    front: { label: '01', title: 'PadhAI',         subtitle: 'BIAS Exam Intelligence', body: 'AI-powered syllabus analysis crafted exclusively for BIAS students. Upload your PDF and let AI do the rest.',        tag: 'Getting Started' },
    back:  { label: '02', title: 'Syllabus Upload', subtitle: 'Drop · Scan · Analyze',  body: 'Upload your BIAS syllabus PDF. Our OCR engine extracts every topic, unit, and chapter in seconds.',                    tag: 'Step 1 of 4'     },
  },
  {
    id: 1,
    front: { label: '03', title: 'Topic Heatmap',  subtitle: 'Frequency Analysis',     body: 'Visualize which topics appear most in 5 years of BIAS past papers. Darker shade = very high probability.',             tag: 'Step 2 of 4'     },
    back:  { label: '04', title: 'AI Priority Rank', subtitle: 'Smart Topic Scoring',  body: 'Every topic is scored using NLP + historical frequency. Top-ranked topics have 94% prediction accuracy.',              tag: 'Step 3 of 4'     },
  },
  {
    id: 2,
    front: { label: '05', title: 'Question Bank',  subtitle: '127 AI-Generated Qs',   body: 'Get probable exam questions generated by AI — difficulty level, marks, and likelihood score included.',                tag: 'Step 4 of 4'     },
    back:  { label: '06', title: 'Start Predicting', subtitle: 'Your Exam Awaits',     body: 'Join 500+ BIAS students who already use PadhAI to ace their semester exams with precision.',                           tag: 'Free Forever'    },
  },
];

// ── Page Face ─────────────────────────────────────────────────────────────────
const PageFace = ({ data, isFront }) => (
  <div style={{
    width: '100%', height: '100%',
    background: isFront ? '#ffffff' : '#f5f5f5',
    borderRadius: isFront ? '3px 14px 14px 3px' : '14px 3px 3px 14px',
    padding: '26px 22px',
    display: 'flex', flexDirection: 'column', gap: '12px',
    boxSizing: 'border-box', position: 'relative', overflow: 'hidden',
    backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden',
  }}>
    {/* Ruled lines */}
    <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none', opacity: 0.10 }}>
      {Array.from({ length: 14 }).map((_, i) => (
        <div key={i} style={{ position: 'absolute', left: '22px', right: '22px', top: `${70 + i * 15}px`, height: '1px', background: '#000' }} />
      ))}
    </div>
    {/* Corner label */}
    <div style={{ position: 'absolute', top: '14px', right: '16px', fontFamily: 'Orbitron, monospace', fontSize: '9px', fontWeight: 800, color: '#ccc', letterSpacing: '0.12em' }}>{data.label}</div>
    {/* Tag */}
    <div style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', background: '#f0f0f0', border: '1px solid #e0e0e0', borderRadius: '20px', padding: '3px 10px', width: 'fit-content' }}>
      <div style={{ width: '5px', height: '5px', borderRadius: '50%', background: '#333' }} />
      <span style={{ fontSize: '9px', fontFamily: 'Space Grotesk, sans-serif', color: '#444', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase' }}>{data.tag}</span>
    </div>
    {/* Title */}
    <div>
      <h3 style={{ fontFamily: 'Orbitron, monospace', fontWeight: 800, fontSize: '15px', color: '#0a0a0a', lineHeight: 1.2, margin: 0 }}>{data.title}</h3>
      <p style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: '10px', color: '#777', fontWeight: 600, margin: '4px 0 0', letterSpacing: '0.06em', textTransform: 'uppercase' }}>{data.subtitle}</p>
    </div>
    {/* Body */}
    <p style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: '11.5px', color: '#555', lineHeight: 1.7, margin: 0, flex: 1, position: 'relative', zIndex: 1 }}>{data.body}</p>
    {/* Dash */}
    <div style={{ display: 'flex', gap: '3px', alignItems: 'center' }}>
      <div style={{ width: '24px', height: '2px', background: '#0a0a0a', borderRadius: '1px' }} />
      <div style={{ width: '6px', height: '2px', background: '#ccc', borderRadius: '1px' }} />
    </div>
  </div>
);

// ── Book Page (turning) ───────────────────────────────────────────────────────
const BookPage = ({ page, angle, zIndex }) => {
  const clamped = Math.max(0, Math.min(180, angle));
  return (
    <div style={{
      position: 'absolute', inset: 0,
      transformOrigin: 'left center',
      transform: `rotateY(${-clamped}deg)`,
      transformStyle: 'preserve-3d',
      transition: 'transform 0.20s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      zIndex, willChange: 'transform',
    }}>
      <div style={{ position: 'absolute', inset: 0, backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden' }}>
        <PageFace data={page.front} isFront={true} />
      </div>
      <div style={{ position: 'absolute', inset: 0, transform: 'rotateY(180deg)', backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden' }}>
        <PageFace data={page.back} isFront={false} />
      </div>
    </div>
  );
};

// ── Book3D — fully scroll-driven, no hover ────────────────────────────────────
const Book3D = () => {
  const [scrollProgress, setScrollProgress] = useState(0);

  // ── Listen to window scroll — map hero scroll → 0…1 ──────────────────────
  useEffect(() => {
    const onScroll = () => {
      // The hero section is full-screen height.
      // We map the first 80% of hero-section scroll to 0→1.
      const heroEl = document.getElementById('home');
      if (!heroEl) return;
      const heroH = heroEl.offsetHeight;
      const scrollY = window.scrollY;
      // When scrollY = 0  → progress = 0
      // When scrollY = heroH * 0.8 → progress = 1
      const raw = scrollY / (heroH * 0.7);
      setScrollProgress(Math.max(0, Math.min(1, raw)));
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll(); // init
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  // ── Derive book rotation from scroll ─────────────────────────────────────
  // Book slowly rotates on Y axis (0 → -25 deg) while pages turn
  const bookRotateX = 8 - scrollProgress * 4;   // slight tilt changes with scroll
  const bookRotateY = -4 - scrollProgress * 18;  // main rotation driven by scroll

  const getPageAngle = useCallback((pageIndex) => {
    const total = pages.length;
    const seg   = 1 / total;
    const start = pageIndex * seg;
    const ovlap = seg * 0.2;
    const local = Math.max(0, Math.min(1, (scrollProgress - (start - ovlap)) / (seg + ovlap)));
    return local * 180;
  }, [scrollProgress]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '18px', userSelect: 'none' }}>

      {/* Scroll hint pill */}
      <motion.div
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 1.4, duration: 0.6 }}
        style={{
          display: 'flex', alignItems: 'center', gap: '8px',
          background: '#f5f5f5', border: '1px solid #e0e0e0',
          borderRadius: '100px', padding: '6px 16px',
        }}
      >
        <motion.div
          animate={{ y: [0, 5, 0] }}
          transition={{ duration: 1.4, repeat: Infinity, ease: 'easeInOut' }}
          style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#0a0a0a' }}
        />
        <span style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: '11px', color: '#555', fontWeight: 600 }}>
          Scroll to turn pages
        </span>
      </motion.div>

      {/* Book — NO hover, pure scroll-driven */}
      <div style={{ perspective: '1400px', padding: '20px 30px 36px' }}>
        <div
          style={{
            transformStyle: 'preserve-3d',
            position: 'relative',
            width: '260px',
            height: '340px',
            transform: `rotateX(${bookRotateX}deg) rotateY(${bookRotateY}deg)`,
            transition: 'transform 0.25s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
            willChange: 'transform',
          }}
        >
          {/* Drop shadow */}
          <div style={{
            position: 'absolute', bottom: '-32px', left: '8%', right: '8%',
            height: '40px', borderRadius: '50%',
            background: `radial-gradient(ellipse, rgba(0,0,0,${0.18 + scrollProgress * 0.18}), transparent 70%)`,
            filter: 'blur(14px)', zIndex: 0,
          }} />

          {/* Back cover */}
          <div style={{
            position: 'absolute', inset: 0,
            borderRadius: '3px 14px 14px 3px',
            background: 'linear-gradient(135deg, #111, #1a1a1a)',
            border: '1px solid #333',
            transform: 'translateZ(-4px)', zIndex: 0,
          }} />

          {/* Spine */}
          <div style={{
            position: 'absolute', left: 0, top: 0, bottom: 0, width: '26px',
            background: 'linear-gradient(180deg, #0a0a0a, #1a1a1a)',
            borderRadius: '14px 2px 2px 14px',
            transform: 'translateX(-13px) rotateY(-90deg) translateZ(13px)',
            transformOrigin: 'right center',
            display: 'flex', flexDirection: 'column',
            alignItems: 'center', justifyContent: 'center', gap: '6px',
            boxShadow: '0 0 14px rgba(0,0,0,0.5)',
          }}>
            <div style={{
              writingMode: 'vertical-rl', textOrientation: 'mixed',
              fontFamily: 'Orbitron, monospace', fontSize: '8px', fontWeight: 800,
              color: '#aaa', letterSpacing: '0.18em', textTransform: 'uppercase',
            }}>PadhAI</div>
            <div style={{ width: '12px', height: '1px', background: '#444' }} />
          </div>

          {/* Page stack */}
          {[3, 2, 1].map(offset => (
            <div key={offset} style={{
              position: 'absolute', inset: 0,
              background: `hsl(0,0%,${92 - offset * 2}%)`,
              borderRadius: '14px 3px 3px 14px',
              transform: `translateZ(${offset}px)`,
              boxShadow: 'inset -1px 0 4px rgba(0,0,0,0.08)',
            }} />
          ))}

          {/* Turning pages — back to front */}
          {[...pages].reverse().map((page, rIdx) => {
            const idx   = pages.length - 1 - rIdx;
            const angle = getPageAngle(idx);
            return <BookPage key={page.id} page={page} angle={angle} zIndex={10 + idx} />;
          })}

          {/* Edge highlight */}
          <div style={{
            position: 'absolute', inset: '-1px', borderRadius: '16px',
            border: '1px solid rgba(0,0,0,0.08)',
            pointerEvents: 'none', zIndex: 100,
          }} />
        </div>
      </div>

      {/* Progress dots */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
        <FiBookOpen style={{ color: '#bbb', fontSize: '13px' }} />
        <div style={{ display: 'flex', gap: '5px' }}>
          {pages.map((_, i) => {
            const angle = getPageAngle(i);
            const turned = angle > 10;
            return (
              <motion.div
                key={i}
                animate={{ scale: turned ? 1.3 : 1 }}
                style={{
                  width: '7px', height: '7px', borderRadius: '50%',
                  background: turned ? '#0a0a0a' : '#ddd',
                  transition: 'background 0.3s',
                }}
              />
            );
          })}
        </div>
        <span style={{ fontFamily: 'Orbitron, monospace', fontSize: '9px', color: '#bbb', letterSpacing: '0.1em' }}>
          {Math.round(scrollProgress * 100)}%
        </span>
      </div>
    </div>
  );
};

export default Book3D;
